export const REGISTER_START="REGISTER_START";
export const REGISTER_SUCCSESS="REGISTER_SUCCSESS";
export const REGISTER_ERROR="REGISTER_ERROR";

export const LOGIN_START="LOGIN_START";
export const LOGIN_SUCCSESS="LOGIN_SUCCSESS";
export const LOGIN_ERROR="LOGIN_ERROR";

export const LOGOUT_START="LOGOUT_START";
export const LOGOUT_SUCCSESS="LOGOUT_SUCCSESS";
export const LOGOUT_ERROR="LOGOUT_ERROR";
